"""
Django settings for TTSX project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7(0v6_0on#&o$sy0w@89q78e36m*z7yp*g^rr$@4)now477y(&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Seller',
    'Buyer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TTSX.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TTSX.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "static")

# 钉钉机器人验证码
DING_URL = "https://oapi.dingtalk.com/robot/send?access_token=58c65deca62300bfbb04a6c0db60e6b740d26f791714b8e651478e940d4f4996"

# 支付宝沙箱支付

alipay_public_key_string = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA91XOUtAt6npBHAsZJbidDcBWVNGGsMN3IdoW2II23HUW+BjMSXv0LK17ZB5DgslIHDmz3+jbPVGHujJXiVoHdj6llmg3uUkOgI9QeK3pFdppLvQNv+av6JaL7wXS9bM7n0jJBqioivg5zKtcABr70cXCFD57z58U3MFVkxhxZuQx5MSpY/nJy0CTXc6g89XvZT7Vtgx0feHOwC/VBOenltVkSalcjofEjQJEQaK2yXR6EIiSSnDq8DUY3NjH6D/F5xdD1lFkc6OFZHnovi0UOaTW/63Uw5jNpa8QDCjZWj/2U5Oyw9NiWBn4EWxMk8g+D5yFVmbXwRfV9LoWekO3bQIDAQAB
-----END PUBLIC KEY-----"""

alipay_private_key_string = """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA91XOUtAt6npBHAsZJbidDcBWVNGGsMN3IdoW2II23HUW+BjMSXv0LK17ZB5DgslIHDmz3+jbPVGHujJXiVoHdj6llmg3uUkOgI9QeK3pFdppLvQNv+av6JaL7wXS9bM7n0jJBqioivg5zKtcABr70cXCFD57z58U3MFVkxhxZuQx5MSpY/nJy0CTXc6g89XvZT7Vtgx0feHOwC/VBOenltVkSalcjofEjQJEQaK2yXR6EIiSSnDq8DUY3NjH6D/F5xdD1lFkc6OFZHnovi0UOaTW/63Uw5jNpa8QDCjZWj/2U5Oyw9NiWBn4EWxMk8g+D5yFVmbXwRfV9LoWekO3bQIDAQABAoIBAQDuCEZorLGD1+SReJzbELEVauWq+3sE4xjkG1+hPrBNuuJAIp14mzKDTPJTiEywscYUY/QYqaFVggF90LUuGtbTlbcG6YW3a/fpAgQQIE8SGQDhjz8sUHc7AKfrgU9l5viacxIEtox+MiZuMvx3nYB8gjYmBXxidFc/nVEeH4gD2/VP328tcdntyGbgLoCXfq2SR3nczcUvYFNjEa/FNEeUmv3X1QMTFkmqNUyJzpYkdDnsas6esLG9IAK+DP+DVam+a3TZ65KQdhMzU9vcQqJNYxSe5juT8UUJyE/sYfgt9oTIiQ2NGXZTBQu8t8+6vH0+izjPkgIeswXZopsG8Z6BAoGBAP0FT+qUPw4a8cpDKhggOQjqdbOxBz118Pd4apuQMw9T2DCTecBaBX3NfaSkUdCSpd16UBGY8HCLSUyqGfENXRxuEseDHmo4yytx+bVsZj6Df0dbIPjT119zod+C+t69ELJaMBCB2zIbDNUo8Oy4vWs9MByAGvFe2kRu+/FQjnvXAoGBAPo/WwhF60eTExXUjIC/36PH2darf/JVlrDSNJZ9QuUd1P5A0ydoOrlNnVbA7H/rLEOdNxgZSArEs/LIDCE2PL94q/T2+vJz9W4rwCvZxUg0HJdMQB7Zn480uZH+hYB1grRTu1hk4S9olL1VDMsQX+383Gdt9M5q21uzCadEaZ5bAoGAEcJlsZlmM59AiWndcoQQfMe4KzypvW6h0zzofrLIYrMH4aD4Ur/+0q2xu/SsqW8hpUIIjLOnbL7aDj+CQqElf/FZ8BcL83i5CfueA1Xwd0LTlDaZQd3cqB59piqTYT70BRC/fukecY3kgLG292agJP7OebGkMnzt5Q/FL1LwLVECgYAYwTmtGNWMcAUcTLlVZyWlWvi2nqJ6g3LzrOec12lNpuTR/fGlXU8p036z/UOn58iqK5wumxmgTxMJ+jYQ9v+NZU+FXQU4BLaLnnJVJCa63MTTRqy1IIwDK5EL2ySzr2wtkHbg6KHKActs60Pntof2z+Oxq5Pi83kdmhljXYYhLwKBgEuzv+YSThs1gHkHPofrFIRkBzWir2qMFFLmgz1NtaBUXaLyPQ4+J90r5xaokHA86Yv6DNQecLaDAQ5oXvhgSsL8o5fpbAgvcZQRb3TPboHrdmjYci6VfZbk0qmOP6ogJxkRvWUJZ8OTdcC7nM0SRrkx0pUCPGt1izYQgvlDt7nS
-----END RSA PRIVATE KEY-----"""
